# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  l04:
    dir: './Lecciones/L04'
    cmds:
      - quarto preview L04.qmd
  l05:
    dir: './Lecciones/L05'
    cmds:
      - quarto preview L05.qmd
